# Generated by Django 5.2.9 on 2026-01-06 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='agent_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='camera_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='cheating_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='communication_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='current_stage',
            field=models.CharField(default='greeting', max_length=50),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='evaluation_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='microphone_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='parsed_resume_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='responses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='technical_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='cheating_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='CheatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Lost Focus'), ('VISIBILITY_HIDDEN', 'Page Hidden'), ('CAMERA_OFF', 'Camera Turned Off'), ('MIC_OFF', 'Microphone Turned Off'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('COPY_PASTE', 'Copy/Paste Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('NO_FACE', 'No Face Detected')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('PERSONAL', 'Personal'), ('RESUME', 'Resume-based'), ('TECHNICAL', 'Technical'), ('CODING', 'Coding Logic'), ('BEHAVIORAL', 'Behavioral')], max_length=20)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_received_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['asked_at'],
            },
        ),
    ]
