# Generated by Django 5.2.9 on 2026-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interviewsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='first_access_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='last_access_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='link_access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='link_accessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='follow_up_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='was_vague',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
