# Generated by Django 5.2.6 on 2026-02-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_company_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingevent',
            name='event_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Tab Switch'), ('WINDOW_BLUR', 'Window Lost Focus'), ('VISIBILITY_HIDDEN', 'Page Hidden'), ('CAMERA_OFF', 'Camera Turned Off'), ('MIC_OFF', 'Microphone Turned Off'), ('FULLSCREEN_EXIT', 'Exited Fullscreen'), ('COPY_PASTE', 'Copy/Paste Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('NO_FACE', 'No Face Detected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
