# Generated by Django 5.2.6 on 2026-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_alter_cheatingevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='video_recording',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/'),
        ),
    ]
